import { Feather, Ionicons, MaterialCommunityIcons } from '@expo/vector-icons'

export const I = {
  Calendar:   ({ size = 18, color = '#8BA67D', ...p }) => <Feather name="calendar" size={size} color={color} {...p} />,
  Clock:      ({ size = 16, color = '#8BA67D', ...p }) => <Feather name="clock" size={size} color={color} {...p} />,
  MapPin:     ({ size = 16, color = '#8BA67D', ...p }) => <Feather name="map-pin" size={size} color={color} {...p} />,
  Mail:       ({ size = 16, color = '#8BA67D', ...p }) => <Feather name="mail" size={size} color={color} {...p} />,
  Link:       ({ size = 16, color = '#8BA67D', ...p }) => <Feather name="link" size={size} color={color} {...p} />,
  Trophy:     ({ size = 18, color = '#8BA67D', ...p }) => <Ionicons name="trophy-outline" size={size} color={color} {...p} />,
  Plus:       ({ size = 18, color = '#8BA67D', ...p }) => <Feather name="plus" size={size} color={color} {...p} />,
  User:       ({ size = 18, color = '#8BA67D', ...p }) => <Feather name="user" size={size} color={color} {...p} />,
  Check:      ({ size = 16, color = '#8BA67D', ...p }) => <Feather name="check" size={size} color={color} {...p} />,
  ArrowRight: ({ size = 16, color = '#8BA67D', ...p }) => <Feather name="arrow-right" size={size} color={color} {...p} />,
  Leaf:       ({ size = 20, color = '#8BA67D', ...p }) => <MaterialCommunityIcons name="leaf" size={size} color={color} {...p} />,
  Google:     ({ size = 18, color = '#4285F4', ...p }) => <Ionicons name="logo-google" size={size} color={color} {...p} />,
  Logout:     ({ size = 16, color = '#8BA67D', ...p }) => <Feather name="log-out" size={size} color={color} {...p} />,
  X:          ({ size = 16, color = '#8BA67D', ...p }) => <Feather name="x" size={size} color={color} {...p} />,
  Trash:      ({ size = 15, color = '#8BA67D', ...p }) => <Feather name="trash-2" size={size} color={color} {...p} />,
  Refresh:    ({ size = 16, color = '#8BA67D', ...p }) => <Feather name="refresh-cw" size={size} color={color} {...p} />,
  List:       ({ size = 18, color = '#8BA67D', ...p }) => <Feather name="list" size={size} color={color} {...p} />,
  Camera:     ({ size = 16, color = '#8BA67D', ...p }) => <Feather name="camera" size={size} color={color} {...p} />,
  School:     ({ size = 16, color = '#8BA67D', ...p }) => <Ionicons name="school-outline" size={size} color={color} {...p} />,
  Menu:       ({ size = 20, color = '#8BA67D', ...p }) => <Feather name="menu" size={size} color={color} {...p} />,
  Upload:     ({ size = 16, color = '#8BA67D', ...p }) => <Feather name="upload" size={size} color={color} {...p} />,
  ArrowLeft:  ({ size = 20, color = '#8BA67D', ...p }) => <Feather name="arrow-left" size={size} color={color} {...p} />,
  Search:     ({ size = 18, color = '#8BA67D', ...p }) => <Feather name="search" size={size} color={color} {...p} />,
  ChevronDown:({ size = 16, color = '#8BA67D', ...p }) => <Feather name="chevron-down" size={size} color={color} {...p} />,
  // Aliases used by linter-modified components
  Close:      ({ size = 16, color = '#8BA67D', ...p }) => <Feather name="x" size={size} color={color} {...p} />,
  Location:   ({ size = 16, color = '#8BA67D', ...p }) => <Feather name="map-pin" size={size} color={color} {...p} />,
  Edit:       ({ size = 16, color = '#8BA67D', ...p }) => <Feather name="edit-2" size={size} color={color} {...p} />,
  Email:      ({ size = 16, color = '#8BA67D', ...p }) => <Feather name="mail" size={size} color={color} {...p} />,
  Sparkles:   ({ size = 18, color = '#8BA67D', ...p }) => <Ionicons name="sparkles-outline" size={size} color={color} {...p} />,
}
